version: '2'

services:
  redis:
      image: redis

  mongodb:
      image: mongo
      ports:
        - "27019:27017"

  elk_mongo:
      build: ./
      command: sh -c "python ES2mongodb.py && python mongodb2json.py"
      #volumes:
        #- /tmp/sync:/app/src/main/python/sync
      links:
        - redis
        - mongodb

networks:
  default:
    external:
      name: useractionelk_elk

