version: '2'

services:
  redis:
      image: redis

  mongodb:
      image: mongo
      ports:
        - "27019:27017"

  elk_mongo:
      build: ./
      command: sh -c "celery -A pj worker -B -Q es_mongodb -l info"
      #volumes:
        #- /tmp/sync:/app/src/main/python/
      links:
        - redis
        - mongodb

networks:
  default:
    external:
      name: useractionelk_elk

